# Generated by Django 5.1.2 on 2024-11-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trg_trainingmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Instructor Name')),
                ('specialization', models.CharField(max_length=200, verbose_name='Specialization')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('trainings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='trg_trainingmanagement.training', verbose_name='Trainings')),
            ],
        ),
    ]
