# Generated by Django 5.1.2 on 2024-11-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue Date')),
                ('validation_code', models.CharField(max_length=50, unique=True, verbose_name='Validation Code')),
            ],
        ),
    ]
