# Generated by Django 5.1.2 on 2024-11-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trg_certification', '0001_initial'),
        ('trg_participantmanagement', '0001_initial'),
        ('trg_trainingmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='trg_participantmanagement.participant', verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='trg_trainingmanagement.training', verbose_name='Training'),
        ),
    ]
