# Generated by Django 5.1.2 on 2024-11-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ergonomic', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None')], max_length=20)),
                ('biological', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None')], max_length=20)),
                ('chemical', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None')], max_length=20)),
                ('physical', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None')], max_length=20)),
                ('accident', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigation', models.TextField()),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osha_riskanalysis.riskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='RiskIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employees', models.IntegerField()),
                ('area_description', models.TextField()),
                ('equipment_description', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.area')),
            ],
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_identification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osha_riskanalysis.riskidentification'),
        ),
    ]
