# Generated by Django 5.1.2 on 2024-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osha_riskanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='accident',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='biological',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='chemical',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='ergonomic',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='physical',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('None', 'None')], max_length=20),
        ),
    ]
