# Generated by Django 5.1.2 on 2024-11-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_password'),
        ('osha_incidentreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50),
            preserve_default=False,
        ),
    ]
