# Generated by Django 5.1.2 on 2024-11-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_password'),
        ('trg_trainingmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='employees.employee', verbose_name='Employee')),
                ('trainings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trg_trainingmanagement.training', verbose_name='Trainings')),
            ],
        ),
    ]
