from django.db import models
from trg_trainingmanagement.models import Training

class TrainingReport(models.Model):
    REPORT_TYPES = [
        ('attendance', 'Attendance'),
        ('performance', 'Performance'),
        ('feedback', 'Feedback'),
        ('general', 'General Overview'),
    ]

    title = models.CharField(max_length=200, verbose_name="Report Title")
    report_type = models.CharField(
        max_length=50,
        choices=REPORT_TYPES,
        default='general',
        verbose_name="Report Type"
    )
    training = models.ForeignKey(
        Training,
        on_delete=models.CASCADE,
        related_name="reports",
        verbose_name="Related Training",
        null=True,  
        blank=True
    )
    generated_at = models.DateTimeField(auto_now_add=True, verbose_name="Generated At")
    data = models.JSONField(verbose_name="Report Data") 
    created_by = models.CharField(max_length=100, verbose_name="Generated By")

    def __str__(self):
        return f"{self.title} - {self.report_type}"

