# Generated by Django 5.1.2 on 2024-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='applicant_images/')),
                ('about', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.CharField(max_length=500, null=True)),
                ('interactions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
