# Generated by Django 5.1.2 on 2024-11-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('EPI', 'Personal Protective Equipment'), ('EPC', 'Collective Protective Equipment')], max_length=3)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('acquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EPIDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osha_safetyequipmentmanagement.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('observations', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='osha_safetyequipmentmanagement.equipment')),
            ],
        ),
    ]
