# Generated by Django 5.1.2 on 2024-11-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('Health Insurance', 'Health Insurance'), ('Meal Voucher', 'Meal Voucher'), ('Transport Voucher', 'Transport Voucher'), ('Gym Membership', 'Gym Membership'), ('Other', 'Other')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Monthly benefit value', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
    ]
