# Generated by Django 5.1.2 on 2024-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.CharField(max_length=500)),
                ('education', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
